export const defaultBoardState = [
    [
      {
        coordinate: "a1",
        rank: 1,
        file: 1,
        piece: {
          name: "rook",
          color: "white",
          type: "rook",
          value: 5,
          rank: 1,
          file: 1,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "b1",
        rank: 1,
        file: 2,
        piece: {
          name: "knight",
          color: "white",
          type: "knight",
          value: 3,
          rank: 1,
          file: 2,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "c1",
        rank: 1,
        file: 3,
        piece: {
          name: "bishop",
          color: "white",
          type: "bishop",
          value: 3,
          rank: 1,
          file: 3,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "d1",
        rank: 1,
        file: 4,
        piece: {
          name: "queen",
          color: "white",
          type: "queen",
          value: 9,
          rank: 1,
          file: 4,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "e1",
        rank: 1,
        file: 5,
        piece: {
          name: "king",
          color: "white",
          type: "king",
          value: 0,
          rank: 1,
          file: 5,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "f1",
        rank: 1,
        file: 6,
        piece: {
          name: "bishop",
          color: "white",
          type: "bishop",
          value: 3,
          rank: 1,
          file: 6,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "g1",
        rank: 1,
        file: 7,
        piece: {
          name: "knight",
          color: "white",
          type: "knight",
          value: 3,
          rank: 1,
          file: 7,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "h1",
        rank: 1,
        file: 8,
        piece: {
          name: "rook",
          color: "white",
          type: "rook",
          value: 5,
          rank: 1,
          file: 8,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
    ],
    // ---- Rank 2 ----
    // WHITE's eight pawns, mirroring black's rank-7 wall at the other end.
    [
      {
        coordinate: "a2",
        rank: 2,
        file: 1,
        piece: {
          name: "pawn",
          color: "white",
          type: "pawn",
          value: 1,
          rank: 2,
          file: 1,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "b2",
        rank: 2,
        file: 2,
        piece: {
          name: "pawn",
          color: "white",
          type: "pawn",
          value: 1,
          rank: 2,
          file: 2,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "c2",
        rank: 2,
        file: 3,
        piece: {
          name: "pawn",
          color: "white",
          type: "pawn",
          value: 1,
          rank: 2,
          file: 3,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "d2",
        rank: 2,
        file: 4,
        piece: {
          name: "pawn",
          color: "white",
          type: "pawn",
          value: 1,
          rank: 2,
          file: 4,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "e2",
        rank: 2,
        file: 5,
        piece: {
          name: "pawn",
          color: "white",
          type: "pawn",
          value: 1,
          rank: 2,
          file: 5,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "f2",
        rank: 2,
        file: 6,
        piece: {
          name: "pawn",
          color: "white",
          type: "pawn",
          value: 1,
          rank: 2,
          file: 6,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "g2",
        rank: 2,
        file: 7,
        piece: {
          name: "pawn",
          color: "white",
          type: "pawn",
          value: 1,
          rank: 2,
          file: 7,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "h2",
        rank: 2,
        file: 8,
        piece: {
          name: "pawn",
          color: "white",
          type: "pawn",
          value: 1,
          rank: 2,
          file: 8,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
    ],
    // ---- Rank 3 ----
    [
      {
        coordinate: "a3",
        rank: 3,
        file: 1,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "b3",
        rank: 3,
        file: 2,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "c3",
        rank: 3,
        file: 3,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "d3",
        rank: 3,
        file: 4,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "e3",
        rank: 3,
        file: 5,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "f3",
        rank: 3,
        file: 6,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "g3",
        rank: 3,
        file: 7,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "h3",
        rank: 3,
        file: 8,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
    ],
    // ---- Rank 4 ----
    [
      {
        coordinate: "a4",
        rank: 4,
        file: 1,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "b4",
        rank: 4,
        file: 2,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "c4",
        rank: 4,
        file: 3,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "d4",
        rank: 4,
        file: 4,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "e4",
        rank: 4,
        file: 5,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "f4",
        rank: 4,
        file: 6,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "g4",
        rank: 4,
        file: 7,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "h4",
        rank: 4,
        file: 8,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
    ],
    // ---- Rank 5 ----
    [
      {
        coordinate: "a5",
        rank: 5,
        file: 1,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "b5",
        rank: 5,
        file: 2,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "c5",
        rank: 5,
        file: 3,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "d5",
        rank: 5,
        file: 4,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "e5",
        rank: 5,
        file: 5,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "f5",
        rank: 5,
        file: 6,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "g5",
        rank: 5,
        file: 7,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "h5",
        rank: 5,
        file: 8,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
    ],
    // ---- Rank 6 ----
    [
      {
        coordinate: "a6",
        rank: 6,
        file: 1,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "b6",
        rank: 6,
        file: 2,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "c6",
        rank: 6,
        file: 3,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "d6",
        rank: 6,
        file: 4,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "e6",
        rank: 6,
        file: 5,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "f6",
        rank: 6,
        file: 6,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "g6",
        rank: 6,
        file: 7,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "h6",
        rank: 6,
        file: 8,
        piece: null,
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
    ],
    // ---- Rank 7 ----
    // BLACK's eight pawns fill the whole rank, shielding the back rank behind them.
    [
      {
        coordinate: "a7",
        rank: 7,
        file: 1,
        piece: {
          name: "pawn",
          color: "black",
          type: "pawn",
          value: 1,
          rank: 7,
          file: 1,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "b7",
        rank: 7,
        file: 2,
        piece: {
          name: "pawn",
          color: "black",
          type: "pawn",
          value: 1,
          rank: 7,
          file: 2,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "c7",
        rank: 7,
        file: 3,
        piece: {
          name: "pawn",
          color: "black",
          type: "pawn",
          value: 1,
          rank: 7,
          file: 3,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "d7",
        rank: 7,
        file: 4,
        piece: {
          name: "pawn",
          color: "black",
          type: "pawn",
          value: 1,
          rank: 7,
          file: 4,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "e7",
        rank: 7,
        file: 5,
        piece: {
          name: "pawn",
          color: "black",
          type: "pawn",
          value: 1,
          rank: 7,
          file: 5,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "f7",
        rank: 7,
        file: 6,
        piece: {
          name: "pawn",
          color: "black",
          type: "pawn",
          value: 1,
          rank: 7,
          file: 6,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "g7",
        rank: 7,
        file: 7,
        piece: {
          name: "pawn",
          color: "black",
          type: "pawn",
          value: 1,
          rank: 7,
          file: 7,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "h7",
        rank: 7,
        file: 8,
        piece: {
          name: "pawn",
          color: "black",
          type: "pawn",
          value: 1,
          rank: 7,
          file: 8,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
    ],
    // ---- Rank 8 (top row) ----
    // BLACK's back rank. The standard order is rook, knight, bishop, QUEEN, KING,
    // bishop, knight, rook. The easy way to remember the middle two: the queen
    // starts on the square matching her OWN colour (black queen -> the dark d8),
    // and the king takes the square beside her on e8.
    [
      {
        coordinate: "a8",
        rank: 8,
        file: 1,
        piece: {
          name: "rook",
          color: "black",
          type: "rook",
          value: 5,
          rank: 8,
          file: 1,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "b8",
        rank: 8,
        file: 2,
        piece: {
          name: "knight",
          color: "black",
          type: "knight",
          value: 3,
          rank: 8,
          file: 2,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "c8",
        rank: 8,
        file: 3,
        piece: {
          name: "bishop",
          color: "black",
          type: "bishop",
          value: 3,
          rank: 8,
          file: 3,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "d8",
        rank: 8,
        file: 4,
        piece: {
          name: "queen",
          color: "black",
          type: "queen",
          value: 9,
          rank: 8,
          file: 4,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "e8",
        rank: 8,
        file: 5,
        piece: {
          name: "king",
          color: "black",
          type: "king",
          value: 0,
          rank: 8,
          file: 5,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "f8",
        rank: 8,
        file: 6,
        piece: {
          name: "bishop",
          color: "black",
          type: "bishop",
          value: 3,
          rank: 8,
          file: 6,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "g8",
        rank: 8,
        file: 7,
        piece: {
          name: "knight",
          color: "black",
          type: "knight",
          value: 3,
          rank: 8,
          file: 7,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
      {
        coordinate: "h8",
        rank: 8,
        file: 8,
        piece: {
          name: "rook",
          color: "black",
          type: "rook",
          value: 5,
          rank: 8,
          file: 8,
          isSelected: false,
        },
        isHovered: false,
        theme: "default",
        isHighlighted: false,
      },
    ],
  ];